In [2]:
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
import numpy as np
NUM_TO_AUGMENT = 5

In [3]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(50000, 32, 32, 3) (50000, 1)
(10000, 32, 32, 3) (10000, 1)


keras.preprocessing.image.ImageDataGenerator：

用以生成一个batch的图像数据，支持实时数据提升。训练时该函数会无限生成数据，直到达到规定的epoch次数为止。

In [5]:
datagen = ImageDataGenerator(
#     featurewise_center=True,
#     featurewise_std_normalization=True,
    rotation_range=40,
    zoom_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')

# compute quantities required for featurewise normalization
# (std, mean, and principal components if ZCA whitening is applied)
# datagen.fit(x_train)

flow(self, X, y, batch_size=32, shuffle=True, seed=None, save_to_dir=None, save_prefix='', save_format='png')：

接收numpy数组和标签为参数,生成经过数据提升或标准化后的batch数据,并在一个无限循环中不断的返回batch数据

In [10]:
xtas = []
for i in range(10):
    num_aug = 0
    x = x_train[i] #(32,32,3)
    x = x.reshape((1,)+x.shape) #(1,32,32,3)
    for x_aug in datagen.flow(x, batch_size=1, save_to_dir='preview', save_prefix='cifar', save_format='jpg'):
        if num_aug >= NUM_TO_AUGMENT:
            break
        xtas.append(x_aug[0])
        num_aug += 1
print(np.shape(xtas))

(50, 32, 32, 3)
[[[ 158.  130.  104.]
  [ 159.  129.  102.]
  [ 168.  136.  108.]
  ..., 
  [ 119.   76.   33.]
  [ 128.   82.   41.]
  [ 137.  100.   68.]]

 [[ 158.  130.  104.]
  [ 159.  129.  102.]
  [ 168.  136.  108.]
  ..., 
  [ 132.   91.   51.]
  [ 154.  112.   77.]
  [ 154.  120.   89.]]

 [[ 158.  132.  108.]
  [ 158.  130.  104.]
  [ 159.  129.  102.]
  ..., 
  [ 156.  114.   82.]
  [ 154.  112.   77.]
  [ 155.  117.   82.]]

 ..., 
 [[ 128.  102.   41.]
  [ 128.  102.   41.]
  [ 151.  128.   54.]
  ..., 
  [ 159.  120.   90.]
  [ 153.  114.   84.]
  [ 161.  123.   92.]]

 [[ 151.  128.   54.]
  [ 151.  128.   54.]
  [ 140.  121.   54.]
  ..., 
  [ 159.  120.   90.]
  [ 153.  114.   84.]
  [ 161.  123.   92.]]

 [[ 151.  128.   54.]
  [ 140.  121.   54.]
  [ 140.  121.   54.]
  ..., 
  [ 159.  120.   90.]
  [ 159.  120.   90.]
  [ 153.  114.   84.]]]
