## 导包

In [1]:
# from keras import backend as K
from keras.models import Sequential
from keras.layers.core import Flatten, Dense, Dropout
from keras.layers.convolutional import Conv2D, MaxPooling2D, ZeroPadding2D
from keras.optimizers import SGD
import cv2 #opencv
import numpy as np

Using TensorFlow backend.


In [8]:
import keras
print(keras.__version__)

2.1.0


## 构建模型

In [2]:
# define a VGG16 network

def VGG_16(weights_path=None):
    model = Sequential()
    model.add(ZeroPadding2D((1,1),input_shape=(224,224,3)))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(128, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(256, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(256, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(256, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Conv2D(512, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(Flatten())

    #top layer of the VGG net
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(1000, activation='softmax'))

    if weights_path:
        model.load_weights(weights_path)

    return model

In [3]:
# def VGG_16(weights_path=None):
#     model = Sequential()
#     model.add(Conv2D(64, (3, 3), padding='same', activation='relu', input_shape=(224,224,3)))
#     model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
#     model.add(MaxPooling2D((2,2), strides=(2,2)))

#     model.add(Conv2D(128, (3, 3), padding='same', activation='relu'))
#     model.add(Conv2D(128, (3, 3), padding='same', activation='relu'))
#     model.add(MaxPooling2D((2,2), strides=(2,2)))

#     model.add(Conv2D(256, (3, 3), padding='same', activation='relu'))
#     model.add(Conv2D(256, (3, 3), padding='same', activation='relu'))
#     model.add(Conv2D(256, (3, 3), padding='same', activation='relu'))
#     model.add(MaxPooling2D((2,2), strides=(2,2)))

#     model.add(Conv2D(512, (3, 3), padding='same', activation='relu'))
#     model.add(Conv2D(512, (3, 3), padding='same', activation='relu'))
#     model.add(Conv2D(512, (3, 3), padding='same', activation='relu'))
#     model.add(MaxPooling2D((2,2), strides=(2,2)))

#     model.add(Conv2D(512, (3, 3), padding='same', activation='relu'))
#     model.add(Conv2D(512, (3, 3), padding='same', activation='relu'))
#     model.add(Conv2D(512, (3, 3), padding='same', activation='relu'))
#     model.add(MaxPooling2D((2,2), strides=(2,2)))

#     model.add(Flatten())

#     #top layer of the VGG net
#     model.add(Dense(4096, activation='relu'))
#     model.add(Dropout(0.5))
#     model.add(Dense(4096, activation='relu'))
#     model.add(Dropout(0.5))
#     model.add(Dense(1000, activation='softmax'))

#     if weights_path:
#         model.load_weights(weights_path)

#     return model

In [10]:
x = np.array([[1,2,3],[4,5,6]])
print(x,x.shape)
print(x.ravel())
x = np.expand_dims(x,axis=0)
print(x,x.shape)
print(x.ravel())

[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6]
[[[1 2 3]
  [4 5 6]]] (1, 2, 3)
[1 2 3 4 5 6]


## 导入图片

In [12]:
im = cv2.resize(cv2.imread('input_imgs/cat.jpg'), (224, 224)).astype(np.float32)
# im = im.transpose((2,0,1))
im = np.expand_dims(im, axis=0) #1*224*244
# K.set_image_dim_ordering("th")
print(im.shape)

(1, 224, 224, 3)


## 编译模型

In [6]:
# Test pretrained model
model = VGG_16('vgg16_weights_tf.h5')
optimizer = SGD(lr=0.1,decay=1e-6,momentum=0.9,nesterov=True)
model.compile(optimizer=optimizer, loss='categorical_crossentropy')

## 预测

In [13]:
out = model.predict(im)
print (np.argmax(out))

283
